# Configuration for Salesforce_DimOrder pipeline
entity:
  name: Salesforce_DimOrder
  curated_name: Salesforce_DimOrder
  description: "Data pipeline for Salesforce_DimOrder entity"

processing:
  engine: spark
  version: "3.3.0"
  executor_memory: "4g"
  driver_memory: "2g"
  executor_cores: 2

storage:
  raw_bucket: "raw-data-bucket"
  curated_bucket: "curated-data-bucket"
  consumption_bucket: "consumption-data-bucket"

quality:
  enabled: true
  rules_file: "quality_rules.yaml"
  alert_on_failure: true

monitoring:
  metrics_enabled: true
  log_level: "INFO"
  alert_email: "data-team@company.com"